# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('sta', models.CharField(max_length=1)),
                ('description', models.TextField()),
            ],
        ),
    ]
