# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISayLight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip',
            field=models.CharField(default='192.168.12.1', max_length=15),
            preserve_default=False,
        ),
    ]
