# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISayLight', '0002_device_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.CharField(max_length=22),
        ),
    ]
