# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ISayLight', '0003_auto_20170914_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='update_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
