# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISayLight', '0004_device_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='update_time',
            field=models.DateTimeField(),
        ),
    ]
