# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISayLight', '0005_auto_20170914_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
